apiVersion: v1
kind: List
items:
  - apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: wordpress
      namespace: default
    spec:
      healthChecks:
        - apiVersion: apps/v1
          kind: Deployment
          name: wordpress
          namespace: default
      images:
        - name: wordpress
          newName: wordpress
          newTag: "6-fpm-alpine"
      interval: 30s
      path: applications/wordpress-mariadb
      prune: true
      retryInterval: 10s
      sourceRef:
        kind: GitRepository
        name: gitops-demo
        namespace: flux-system
      suspend: true
      targetNamespace: default
      timeout: 1m
      wait: true
