apiVersion: v1
kind: List
items:
  - apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: wordpress
      namespace: default
    spec:
      healthChecks:
        - apiVersion: apps/v1
          kind: Deployment
          name: wordpress
          namespace: default
      images:
        - name: wordpress
          newName: wordpress
          # newTag: "6-fpm-alpine"
          newTag: nonexistent-tag
      interval: 30s
      path: applications/wordpress-mysql
      prune: true
      retryInterval: 10s
      sourceRef:
        kind: GitRepository
        name: gitops-demo
        namespace: flux-system
      suspend: false
      targetNamespace: default
      timeout: 10m
      wait: true
  - apiVersion: notification.toolkit.fluxcd.io/v1beta2
    kind: Alert
    metadata:
      name: wordpress
      namespace: flux-system
    spec:
      eventSeverity: error
      eventSources:
      - kind: Kustomization
        name: wordpress
        namespace: default
      providerRef:
        name: discord
      summary: Wordpress Reconciliation Ran Into Issue!
