resources:
  - mariadb-secret.yml
  - mariadb-configmap.yml
  - mariadb-sts.yml
  - mariadb-svc.yml
  - wordpress-deployment.yml
  - wordpress-svc.yml
  - wordpress-ingress.yml

images:
  - name: wordpress
    newName: wordpress
    newTag: "6"
  - name: mariadb
    newName: mariadb
    newTag: 11-jammy
