apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: mariadb
      name: mariadb
  clusterIP: None
  selector:
    app: mariadb
