apiVersion: v1
kind: List
items:
  - apiVersion: notification.toolkit.fluxcd.io/v1beta2
    kind: Alert
    metadata:
      name: gitops
      namespace: flux-system
    spec:
      eventSeverity: error
      eventSources:
        - kind: Kustomization
          name: '*'
          namespace: '*'
      providerRef:
        name: discord
      summary: Reconciliation Ran Into Issue!
