apiVersion: v1
kind: List
items:
  - apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: gitops
      namespace: flux-system
    spec:
      interval: 30s
      path: kubernetes/gitops/
      prune: true
      retryInterval: 10s
      sourceRef:
        kind: GitRepository
        name: gitops-demo
        namespace: flux-system
      suspend: false
      timeout: 1m
      wait: true
